const Menu_data = [
  {
    id: 1,
    image: "../images/Badam.jpg",
    name: "Badam",
    category: "DryFruits",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 2,
    image: "../images/maggi.jpg",
    name: "Kaju",
    category: "DryFruits",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 3,
    image: "../images/maggi.jpg",
    name: "Kishmish",
    category: "DryFruits",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 4,
    image: "../images/maggi.jpg",
    name: "Kesar",
    category: "DryFruits",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 5,
    image: "../images/maggi.jpg",
    name: "Walnuts",
    category: "DryFruits",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 6,
    image: "../images/maggi.jpg",
    name: "bhakar_wadi",
    category: "Farsan",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 7,
    image: "../images/bhujiya_sing.jpg",
    name: "maggi",
    category: "Farsan",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 8,
    image: "../images/gathiya.jpg",
    name: "maggi",
    category: "Farsan",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 9,
    image: "../images/chanadaal.jpg",
    name: "maggi",
    category: "Farsan",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 10,
    image: "../images/banana_waffer.jpg",
    name: "banana_waffer",
    category: "Farsan",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 11,
    image: "../images/gulab_jamun.jpg",
    name: "gulab_jamun",
    category: "Sweet",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 12,
    image: "../images/rusgulla.jpg",
    name: "rusgulla",
    category: "Sweet",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 13,
    image: "../images/son_papdi.jpg",
    name: "son_papdi",
    category: "Sweet",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 14,
    image: "../images/kaju_katli.jpg",
    name: "kaju_katli",
    category: "Sweet",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 15,
    image: "../images/peda.jpg",
    name: "peda",
    category: "Sweet",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 16,
    image: "../images/vadapaav.jpg",
    name: "vadapaav",
    category: "Fast food",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 17,
    image: "../images/samosapaav.jpg",
    name: "samosapaav",
    category: "Fast food",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 18,
    image: "../images/sandwich.jpg",
    name: "sandwich",
    category: "Fast food",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 19,
    image: "../images/pani_puri.jpg",
    name: "pani_puri",
    category: "Fast food",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 20,
    image: "../images/paav_bhaji.jpg",
    name: "paav_bhaji",
    category: "Fast food",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
];

export default Menu_data;
