const Menu_data = [
  {
    id: 1,
    image: "../images/lunch/",
    name: "Chicken Spring Rolls",
    category: "starter",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 2,
    image: "../images/starter/Egg-65.jpg",
    name: "Egg 65",
    category: "starter",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 3,
    image: "../images/starter/Chicken-Patties.jpg",
    name: "Chicken Patties",
    category: "starter",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 4,
    image: "../images/starter/Chicken-Manchurian.jpg",
    name: "Chicken Manchurian",
    category: "starter",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 5,
    image: "../images/starter/Chilli-Prawns.jpg",
    name: "Chilli Prawns",
    category: "starter",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 6,
    image: "../images/Fish-and-chicken-pakora.jpg",
    name: "Fish And Chicken Pakora",
    category: "starter",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 7,
    image: "../images/Seekh-kebabs.jpg",
    name: "Seekh Kebabs",
    category: "starter",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 8,
    image: "../images/Keema-samosa.jpg",
    name: "Keema Samosa",
    category: "starter",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 9,
    image: "../images/Soups.jpg",
    name: "Soups",
    category: "soup",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 10,
    image: "../images/butter-chicken.jpg",
    name: "Butter Chicken",
    category: "lunch",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 10,
    image: "../images/chicken-65.jpg",
    name: "Chicken 65",
    category: "lunch",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 10,
    image: "../images/fried-chicken.jpg",
    name: "fried chicken",
    category: "lunch",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 10,
    image: "../images/grilled-chicken.jpg",
    name: "Grilled Chicken",
    category: "lunch",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 10,
    image: "../images/prawn-curry.jpg",
    name: "Prawn Curry",
    category: "lunch",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 10,
    image: "../images/veg_biryani.jpg",
    name: "Veg Biryani",
    category: "lunch",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 11,
    image: "../images/gulab_jamun.jpg",
    name: "gulab_jamun",
    category: "soup",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 12,
    image: "../images/rusgulla.jpg",
    name: "rusgulla",
    category: "soup",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 13,
    image: "../images/son_papdi.jpg",
    name: "son_papdi",
    category: "soup",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 14,
    image: "../images/kaju_katli.jpg",
    name: "kaju_katli",
    category: "soup",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 15,
    image: "../images/peda.jpg",
    name: "peda",
    category: "soup",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 16,
    image: "../images/vadapaav.jpg",
    name: "vadapaav",
    category: "dinner",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 17,
    image: "../images/samosapaav.jpg",
    name: "samosapaav",
    category: "dinner",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 18,
    image: "../images/sandwich.jpg",
    name: "sandwich",
    category: "dinner",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 19,
    image: "../images/pani_puri.jpg",
    name: "pani_puri",
    category: "dinner",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
  {
    id: 20,
    image: "../images/paav_bhaji.jpg",
    name: "paav_bhaji",
    category: "dinner",
    price: "1000 rs",
    description: "Lorem iosum dolor sit amet consectetur adir",
  },
];

export default Menu_data;
